# See https://github.com/cloudflare/wrangler-action for more details on how to use this action.
name: Deploy Worker
on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            PUSHOVER_API_TOKEN
            PUSHOVER_USER_KEY
            TAILSCALE_WEBHOOK_SECRET
        env:
            PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
            PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
            TAILSCALE_WEBHOOK_SECRET: ${{ secrets.TAILSCALE_WEBHOOK_SECRET }}
